labels = ['character_01_ka', 'character_02_kha', 'character_03_ga',
          'character_04_gha', 'character_05_kna', 'character_06_cha',
          'character_07_chha', 'character_08_ja', 'character_09_jha',
          'character_10_yna', 'character_11_taamatar', 'character_12_thaa',
          'character_13_daa', 'character_14_dhaa', 'character_15_adna',
          'character_16_tabala', 'character_17_tha', 'character_18_da',
          'character_19_dha', 'character_20_na', 'character_21_pa',
          'character_22_pha', 'character_23_ba', 'character_24_bha',
          'character_25_ma', 'character_26_yaw', 'character_27_ra',
          'character_28_la', 'character_29_waw', 'character_30_motosaw',
          'character_31_petchiryakha', 'character_32_patalosaw',
          'character_33_ha', 'character_34_chhya', 'character_35_tra',
          'character_36_gya', 'digit_0', 'digit_1', 'digit_2', 'digit_3',
          'digit_4', 'digit_5', 'digit_6', 'digit_7', 'digit_8', 'digit_9']
